name:                esqueleto-postgresql-extra
version:             0.1.0.0
github:              "githubuser/esqueleto-postgresql-extra"
license:             BSD3
author:              "Harpo Roeder"
maintainer:          "roederharpo@protonmail.ch"
copyright:           "2018 Harpo Roeder"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/harporoeder/esqueleto-postgresql-extra#readme>

ghc-options:
- -Wall
- -fno-warn-orphans
- -fno-warn-name-shadowing

dependencies:
- base >= 4.7 && < 5
- persistent
- persistent-postgresql >= 2.8.2
- uuid
- aeson
- bytestring
- esqueleto >= 2.6.0
- text
- base16-bytestring

library:
  source-dirs: src
